### PR TITLE
Fix mongoose reliability issue with async/await

### LINKED ISSUE #3: Mongoose buffering when logging in.
### What happened 
A Chill&chat API bug has been logged at: ```15/1/2023 0:26:0 UTC``` or ```1673702760```(UNIX time UTC) on the production server. This will affect all Chill&chat login and database query attempts made from that time stamp onwards.  The API produced the following logs regarding the crash which is listed below:
```
ERROR: [15/1/2023 0:26:0] MongooseError: Operation `users.findOne()` buffering timed out after 10000ms
(node:196) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/
    at NativeConnection.Connection.openUri (/home/runner/api/node_modules/mongoose/lib/connection.js:825:32)
    at /home/runner/api/node_modules/mongoose/lib/index.js:409:10
    at /home/runner/api/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/runner/api/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)
    at Mongoose._promiseOrCallback (/home/runner/api/node_modules/mongoose/lib/index.js:1262:10)
    at Mongoose.connect (/home/runner/api/node_modules/mongoose/lib/index.js:408:20)
    at Object.<anonymous> (/home/runner/api/src/index.ts:79:10)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module.m._compile (/home/runner/api/node_modules/ts-node/src/index.ts:1618:23)
(node:196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Reproduce
API version: v1.8.4 (latest as of 15/1/2023)
OS: Linux based
Runtime: ```ts-node```

Steps:
- Spin up environment as listed above
- Send POST request to ```/api/login```.

### PR DESCRIPTION
**Pull request by cheng-alvin**
I have fixed the mongoose reliability issue in this branch as mentioned in #3. I have just simply made a catch statement to catch any errors that may occur while connecting such as authentication network or security errors.

### CODE REVIEW

**Comment by cheng-alvin** [comment]
The async function is now complete, tested and verified and is now ready for review and merge.

File: src/utils/connectDatabase.ts [hunk 1]
```diff
@@ -0,0 +1,21 @@
+import mongoose from "mongoose";
+import debug from "./debug";
```
Comment (cheng-alvin) [inline src/utils/connectDatabase.ts:3]: Add line to indicate it's a external code from node_modules

File: src/utils/connectDatabase.ts [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+
+/**
+ * This is the connectDB function, this function will connect the server to the mongoDB database via mongoose.
```
Comment (cheng-alvin) [inline src/utils/connectDatabase.ts]: Correct connectDB to connectDatabase as of the rename

**Review by cheng-alvin — COMMENTED** [review]
Some issues, otherwise all looks good.

File: src/utils/connectDatabase.ts (hunk 1 above)
Comment (cheng-alvin) [reply src/utils/connectDatabase.ts:3]: Fixed in commit number: af650b8

File: src/utils/connectDatabase.ts (hunk 2 above)
Comment (cheng-alvin) [reply src/utils/connectDatabase.ts]: Fixed in commit number: af650b8

**Review by cheng-alvin — COMMENTED** [review]
Unrelated: Please remove ```{ Request,  Response, NextFunction }``` at ```src/index.ts:33``` as it is not used

**Comment by cheng-alvin** [comment]
> Unrelated: Please remove `{ Request, Response, NextFunction }` at `src/index.ts:33` as it is not used

Resolved in 6b0e061e4835fc27b6e04c6598c4afd8673398cc
